Implemented the Spawner tool
threefoldtech/guardians_healthchecker pull request #5
Opened 2024-08-11 10:09 UTC by amr-yassir

### Description
Implemented the Spawner tool

### Related Issues
* [CLI: Spawner #3](https://github.com/threefoldtech/guardians_healthchecker/issues/3)

2024-08-14 11:30 UTC, AbdelrahmanElawady requested changes
Nice work Amr!

Please, add tests. There is not a single test added

2024-08-14 11:30 UTC, AbdelrahmanElawady commented on .github/workflows/spawner.yml
> +# This workflow will build a golang project
this builds, tests and lints the project not just build

2024-08-14 11:30 UTC, AbdelrahmanElawady commented on .github/workflows/spawner.yml
> +  pull_request:
this workflow runs two times for any pr which is unnecessary

2024-08-14 11:30 UTC, AbdelrahmanElawady commented on spawner/README.md
> +| `deployment_strategy` | Strategy for deploying VMs across nodes            | `"100%"`, `"70%"`, `"50%"`, etc.                     |
this is not correct anymore, right?

2024-08-14 11:30 UTC, AbdelrahmanElawady commented on spawner/README.md
> +| Field              | Description                                          | Supported Values                                     |
add which fields are required and which are optional

2024-08-14 11:30 UTC, AbdelrahmanElawady commented on spawner/pkg/spawner/destroyer.go
no need to name the files destroyer, lister and spawner. just destroy, list and spawn

2024-08-14 11:30 UTC, AbdelrahmanElawady commented on spawner/pkg/spawner/destroyer.go
> +func DestroyVms(ctx context.Context, cfg Config, tfPluginClient deployer.TFPluginClient) error {
no need for Vms suffix it is implied. Destroy is enough

2024-08-14 11:30 UTC, AbdelrahmanElawady commented on spawner/cmd/spawn.go
> +		}
this is repeated across all commands. move it to a new function

2024-08-14 11:30 UTC, AbdelrahmanElawady commented on spawner/cmd/setup.go
> +		deployer.WithNetwork("dev"),
why forcing dev network? that is the point of the configuration file is to choose which endpoints instead of threefold's networks

2024-08-14 11:30 UTC, AbdelrahmanElawady commented on spawner/cmd/root.go
> +	listCmd.Flags().StringP("config", "c", "", "path to config file")
you can set a persistent flag on the rootCmd since all commands need that

2024-08-14 11:30 UTC, AbdelrahmanElawady commented on spawner/cmd/destroy.go
> +// destroy command
it is not really a descriptive comment. I think there is no need for it. (same for all commands)

2024-08-14 11:30 UTC, AbdelrahmanElawady commented on spawner/cmd/spawn.go
> +			fmt.Println(errs)
log the error instead of writing it to stdout

2024-08-14 11:30 UTC, AbdelrahmanElawady commented on spawner/internal/parser/validators.go
> +	}
two issues with this, it is used in multiple validation functions so it should be declared separately and it doesn't validate if the relay and chain url are using websocket protocol which should be verified

2024-08-14 11:30 UTC, AbdelrahmanElawady commented on spawner/pkg/spawner/lister.go
> +			return fmt.Errorf("couldn't find any contracts with name %s", name)
should it fail when no vms are deployed?

2024-08-14 11:30 UTC, AbdelrahmanElawady commented on spawner/pkg/spawner/lister.go
> +		}
this won't scale well with 100s of vms. it can be optimized with goroutines and wait groups, check how tfrobot does it

2024-08-14 11:30 UTC, AbdelrahmanElawady commented on spawner/pkg/spawner/lister.go
> +	}
check text/tabwriter package for better handling of tables

2024-08-14 11:30 UTC, AbdelrahmanElawady commented on spawner/pkg/spawner/spawner.go
> +func RunSpawner(ctx context.Context, cfg Config, tfPluginClient deployer.TFPluginClient) error {
rename to Spawn, `run` is implied when you call it

2024-08-14 11:30 UTC, AbdelrahmanElawady commented on spawner/pkg/spawner/spawner.go
> +		log.Fatal().Err(err).Send()
why exiting here? just return the error

2024-08-14 11:30 UTC, AbdelrahmanElawady commented on spawner/pkg/spawner/spawner.go
> +		FarmIDs: []uint64{farm},
add `Healthy` too

2024-08-14 11:30 UTC, AbdelrahmanElawady commented on spawner/pkg/spawner/spawner.go
> +			Memory:      1024,
change to 4 cpu and 8gb memory with 40gb rootfs, make them constants and update the filter too

2024-08-14 11:30 UTC, AbdelrahmanElawady commented on spawner/pkg/spawner/spawner.go
> +		vmCount := calculateVMCount(nodes, cfg.DeploymentStrategy)
return immediately if the number is 0 and log that there is nothing to deploy

2024-08-14 11:30 UTC, AbdelrahmanElawady commented on spawner/pkg/spawner/spawner.go
> +			fmt.Printf("Retrying deployment... Attempt %d/%d\n", i+1, defaultMaxRetries)
remove these printf and use the logger

2024-08-14 11:30 UTC, AbdelrahmanElawady commented on spawner/pkg/spawner/spawner.go
> +func handleFailure(ctx context.Context, err error, cfg Config, tfPluginClient deployer.TFPluginClient, networks []*workloads.ZNet, vms []*workloads.Deployment) error {
the way failures are handled needs some improvements as there are some problems with current implementation:
- the logic for deployments is scattered around the code so multiple places try deploying which make it not very clear
- it doesn't take into account which networks were deployed to try the remaining ones (same for vms)
- it only destroys vms but not networks
- destroy failing should destroy networks with failing vms and return

A better approach is to take into consideration what failed and the remaining workloads to be deployed.

2024-08-14 11:30 UTC, AbdelrahmanElawady commented on spawner/pkg/spawner/types.go
> +	ProjectName string `json:"projectName"`
why there are no json tags for the rest?

2024-08-14 11:30 UTC, AbdelrahmanElawady commented on spawner/pkg/spawner/types.go
> +	ProjectName string `json:"projectName"`
tags have different cases please follow a single one. i.e. `projectName` and `substrate_url`

2024-08-17 13:24 UTC, amr-yassir commented on spawner/cmd/setup.go
> +		deployer.WithNetwork("dev"),
I had to force a network as there is no method in the grid-client to pass the graphQl URL. I already implemented this feature in the client but merging is still in discussion.

2024-08-29 08:58 UTC, AbdelrahmanElawady approved these changes
Looks good. Nice work, Amr!

2024-08-29 09:28 UTC, merged